name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0
    - name: Docker login
      env:
       DOCKER_USER: ${{ secret.DOCKER_USER }}
       DOCKER_PASSWORD: ${{ secret.DOCKER_PASSWORD }}
      run: |
       docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    -  name: Build Dcoker image
       run: |
        docker build -t kr2011/docker-sitio:0.0.2 .
    -  name: Push Docker Image 
       run: |
        docker push kr2011/docker-sitio:0.0.2
 #   - name: Build the Docker image
  #    run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
